version: '2'
services:
  webapp:
    build: ./webapp
    ports:
      - 80:8888
    links:
      - mongodb
    environment:
      db_url: "mongodb://mongodb/hysoft"
      repo: /home/hysoft/venv/webapp

  mongodb:
    build: ./mongodb
    volumes:
      - "db:/db"
    expose:
      - 27017

volumes:
  db:
    driver: local
