version: '2'
services:
  webapp:
    image: hysoftware/hysoftware.net:0.0.9
    ports:
      - 80:8888
    links:
      - mongodb
    environment:
      db_url: "mongodb://mongodb/hysoft"
      repo: "/home/hysoft/venv/webapp"
      address: "[::]:8888"

  mongodb:
    image: hysoftware/mongodb:1.0.0
    volumes:
      - "db:/db"
    expose:
      - 27017

volumes:
  db:
    driver: local
